"""Generate src-tauri/models.toml — the build-time model manifest.

Single source of truth for what the app downloads (connected build, EPI-56)
and bundles (airgap build): for each app-active spec, the published ONNX
repo, a pinned revision (full commit SHA — never a branch), and per-file
sha256 + size for exactly the three files the Rust loader reads.

Hashes come from the HF API where possible (LFS files expose their sha256
oid directly); non-LFS files (tokenizer.json, config.json) are downloaded at
the pinned revision and hashed locally. Requires HF_USERNAME (namespace);
public repos need no token.
"""
from __future__ import annotations

import hashlib
import os
import sys
from pathlib import Path

from huggingface_hub import HfApi, hf_hub_download

from _lib.models import APP_ACTIVE

MANIFEST_PATH = Path(__file__).parent.parent.parent / "src-tauri" / "models.toml"
NEEDED_FILES = ("model.onnx", "tokenizer.json", "config.json")


def sha256_of(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    username = os.environ.get("HF_USERNAME", "").strip()
    if not username:
        print("FAIL: HF_USERNAME not set (run via `task models:manifest`)", file=sys.stderr)
        return 2

    api = HfApi()
    blocks: list[str] = [
        "# Generated by `task models:manifest` — do not edit by hand.",
        "# Pinned model artifacts: what the connected build downloads and the",
        "# airgap build bundles. Revisions are full commit SHAs, never branches",
        "# (security baseline: a tampered ONNX graph is RCE through ONNX Runtime).",
    ]

    for spec in APP_ACTIVE:
        repo = f"{username}/{spec.onnx_repo_slug}"
        print(f"=== {repo} ===")
        info = api.model_info(repo, files_metadata=True)
        revision = info.sha
        by_name = {s.rfilename: s for s in info.siblings}

        blocks += [
            "",
            "[[model]]",
            f"digit_level = {spec.digit_level}",
            f'app_subdir = "{spec.app_subdir}"',
            f'display_name = "{spec.display_name}"',
            f'hf_repo = "{repo}"',
            f'revision = "{revision}"',
        ]
        for name in NEEDED_FILES:
            sibling = by_name.get(name)
            if sibling is None:
                print(f"FAIL: {repo} has no {name}", file=sys.stderr)
                return 1
            if sibling.lfs is not None:
                digest = sibling.lfs.sha256
                size = sibling.lfs.size
            else:
                local = hf_hub_download(repo, name, revision=revision)
                digest = sha256_of(local)
                size = os.path.getsize(local)
            print(f"  {name}: {size} bytes, sha256 {digest[:12]}…")
            blocks += [
                "",
                "[[model.files]]",
                f'name = "{name}"',
                f'sha256 = "{digest}"',
                f"size = {size}",
            ]

    MANIFEST_PATH.write_text("\n".join(blocks) + "\n")
    print(f"\n✓ Manifest written to {MANIFEST_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
