//! Embedded build-time model manifest — the single source of truth for which
//! model artifacts the app uses: pinned HF repos + commit SHAs + per-file
//! sha256/size (see `models.toml`, generated by `task models:manifest`).
//!
//! Consumed by: startup (upserts `models` table rows and resolves their
//! surrogate ids), the connected build's downloader, and the Models panel via
//! `models_status`.

use std::{collections::HashMap, path::Path};

use serde::Deserialize;

#[derive(Deserialize, Debug, Clone)]
pub struct Manifest {
    pub model: Vec<ManifestModel>,
}

#[derive(Deserialize, Debug, Clone)]
pub struct ManifestModel {
    pub digit_level: u8,
    pub app_subdir: String,
    pub display_name: String,
    pub hf_repo: String,
    /// Full commit SHA — never a branch (security baseline).
    pub revision: String,
    pub files: Vec<ManifestFile>,
}

#[derive(Deserialize, Debug, Clone)]
pub struct ManifestFile {
    pub name: String,
    pub sha256: String,
    pub size: u64,
}

/// Parse the manifest embedded at compile time. Errors only on a malformed
/// build artifact, so callers treat failure as unrecoverable.
pub fn load() -> Result<Manifest, String> {
    toml::from_str(include_str!("../models.toml")).map_err(|e| format!("parse models.toml: {e}"))
}

/// Manifest plus the resolved `models.id` per digit level, managed as Tauri
/// state. Ids are resolved once at startup by [`resolve_model_rows`]; every
/// digit-level → model-id lookup goes through here instead of guessing with
/// SQL, so stale rows from earlier model families can coexist in the table
/// (cached results keep their FK) without ever being selected.
#[derive(Debug)]
pub struct ModelCatalog {
    pub manifest: Manifest,
    ids_by_digit: HashMap<u8, i64>,
}

impl ModelCatalog {
    #[must_use]
    pub fn model_id(&self, digit_level: u8) -> Option<i64> {
        self.ids_by_digit.get(&digit_level).copied()
    }

    #[must_use]
    pub fn entry(&self, digit_level: u8) -> Option<&ManifestModel> {
        self.manifest
            .model
            .iter()
            .find(|m| m.digit_level == digit_level)
    }
}

/// Upsert one `models` row per manifest entry (keyed by repo + revision) and
/// return the catalog with resolved ids. Rows from previous families/revisions
/// are left in place — `inference_results` references them.
pub fn resolve_model_rows(
    conn: &duckdb::Connection,
    manifest: Manifest,
) -> Result<ModelCatalog, String> {
    let mut ids_by_digit = HashMap::new();
    for entry in &manifest.model {
        let existing: Option<i64> = conn
            .query_row(
                "SELECT id FROM models WHERE hf_repo = ? AND hf_revision = ?",
                duckdb::params![entry.hf_repo, entry.revision],
                |row| row.get(0),
            )
            .ok();
        let id = match existing {
            Some(id) => id,
            None => conn
                .query_row(
                    "INSERT INTO models
                        (hf_repo, hf_revision, model_type, precision, display_name)
                     VALUES (?, ?, ?, ?, ?) RETURNING id",
                    duckdb::params![
                        entry.hf_repo,
                        entry.revision,
                        entry.digit_level.to_string(),
                        "f32",
                        entry.display_name,
                    ],
                    |row| row.get(0),
                )
                .map_err(|e| format!("insert manifest model row {}: {e}", entry.hf_repo))?,
        };
        ids_by_digit.insert(entry.digit_level, id);
    }
    Ok(ModelCatalog {
        manifest,
        ids_by_digit,
    })
}

/// On-disk presence of one manifest model under `root`: number of files whose
/// size matches the manifest. Full sha256 verification happens during
/// download, not here — hashing 1.8 GB on every status poll is not viable.
#[must_use]
pub fn files_present(root: &Path, entry: &ManifestModel) -> usize {
    entry
        .files
        .iter()
        .filter(|f| {
            std::fs::metadata(root.join(&entry.app_subdir).join(&f.name))
                .map(|m| m.len() == f.size)
                .unwrap_or(false)
        })
        .count()
}

#[cfg(test)]
mod tests {
    use super::load;

    /// The committed models.toml must parse into the typed manifest: three
    /// digit levels, three files each, full-SHA revisions, well-formed
    /// hashes. Catches a hand-edited or truncated manifest at test time
    /// instead of first launch.
    #[test]
    fn embedded_manifest_is_well_formed() -> Result<(), String> {
        let manifest = load()?;
        assert_eq!(manifest.model.len(), 3);
        let mut digits: Vec<u8> = manifest.model.iter().map(|m| m.digit_level).collect();
        digits.sort_unstable();
        assert_eq!(digits, vec![2, 4, 6]);
        for model in &manifest.model {
            assert_eq!(
                model.revision.len(),
                40,
                "{}: revision must be a full commit SHA",
                model.hf_repo
            );
            assert_eq!(model.files.len(), 3, "{}: expected 3 files", model.hf_repo);
            for file in &model.files {
                assert_eq!(
                    file.sha256.len(),
                    64,
                    "{}/{}: malformed sha256",
                    model.hf_repo,
                    file.name
                );
                assert!(file.size > 0);
            }
        }
        Ok(())
    }
}
