//! Embedded build-time model manifest — the single source of truth for which
//! model artifacts the app uses: pinned HF repos + commit SHAs + per-file
//! sha256/size (see `models.toml`, generated by `task models:manifest`).
//!
//! Consumed by: startup (upserts `models` table rows and resolves their
//! surrogate ids), the connected build's downloader, and the Models panel via
//! `models_status`.

use std::{collections::HashMap, path::Path};

use serde::Deserialize;

#[derive(Deserialize, Debug, Clone)]
pub struct Manifest {
    pub model: Vec<ManifestModel>,
}

#[derive(Deserialize, Debug, Clone)]
pub struct ManifestModel {
    pub digit_level: u8,
    pub app_subdir: String,
    pub display_name: String,
    pub hf_repo: String,
    /// Full commit SHA — never a branch (security baseline).
    pub revision: String,
    pub files: Vec<ManifestFile>,
}

#[derive(Deserialize, Debug, Clone)]
pub struct ManifestFile {
    pub name: String,
    pub sha256: String,
    pub size: u64,
}

/// Parse the manifest embedded at compile time. Errors only on a malformed
/// build artifact, so callers treat failure as unrecoverable.
pub fn load() -> Result<Manifest, String> {
    toml::from_str(include_str!("../models.toml")).map_err(|e| format!("parse models.toml: {e}"))
}

/// Manifest plus the resolved `models.id` per digit level, managed as Tauri
/// state. Ids are resolved once at startup by [`resolve_model_rows`]; every
/// digit-level → model-id lookup goes through here instead of guessing with
/// SQL, so stale rows from earlier model families can coexist in the table
/// (cached results keep their FK) without ever being selected.
#[derive(Debug)]
pub struct ModelCatalog {
    pub manifest: Manifest,
    ids_by_digit: HashMap<u8, i64>,
}

impl ModelCatalog {
    #[must_use]
    pub fn model_id(&self, digit_level: u8) -> Option<i64> {
        self.ids_by_digit.get(&digit_level).copied()
    }

    #[must_use]
    pub fn entry(&self, digit_level: u8) -> Option<&ManifestModel> {
        self.manifest
            .model
            .iter()
            .find(|m| m.digit_level == digit_level)
    }

    /// Digit levels the manifest defines, ascending — the set an all-models
    /// run covers (EPI-96).
    #[must_use]
    pub fn levels(&self) -> Vec<u8> {
        let mut levels: Vec<u8> = self.manifest.model.iter().map(|m| m.digit_level).collect();
        levels.sort_unstable();
        levels
    }

    /// Reverse lookup: the digit level whose *active* model row is `model_id`,
    /// `None` when the id belongs to a superseded family/revision.
    #[must_use]
    pub fn level_of(&self, model_id: i64) -> Option<u8> {
        self.levels()
            .into_iter()
            .find(|level| self.model_id(*level) == Some(model_id))
    }
}

/// Upsert one `models` row per manifest entry (keyed by repo + revision) and
/// return the catalog with resolved ids. Rows from previous families/revisions
/// are left in place — `inference_results` references them.
pub fn resolve_model_rows(
    conn: &duckdb::Connection,
    manifest: Manifest,
) -> Result<ModelCatalog, String> {
    let mut ids_by_digit = HashMap::new();
    for entry in &manifest.model {
        let existing: Option<i64> = conn
            .query_row(
                "SELECT id FROM models WHERE hf_repo = ? AND hf_revision = ?",
                duckdb::params![entry.hf_repo, entry.revision],
                |row| row.get(0),
            )
            .ok();
        let id = match existing {
            Some(id) => id,
            None => conn
                .query_row(
                    "INSERT INTO models
                        (hf_repo, hf_revision, model_type, precision, display_name)
                     VALUES (?, ?, ?, ?, ?) RETURNING id",
                    duckdb::params![
                        entry.hf_repo,
                        entry.revision,
                        entry.digit_level.to_string(),
                        "f32",
                        entry.display_name,
                    ],
                    |row| row.get(0),
                )
                .map_err(|e| format!("insert manifest model row {}: {e}", entry.hf_repo))?,
        };
        ids_by_digit.insert(entry.digit_level, id);
    }
    Ok(ModelCatalog {
        manifest,
        ids_by_digit,
    })
}

/// On-disk presence of one manifest model under `root`: number of files whose
/// size matches the manifest. Full sha256 verification happens during
/// download, not here — hashing 1.8 GB on every status poll is not viable.
#[must_use]
pub fn files_present(root: &Path, entry: &ManifestModel) -> usize {
    entry
        .files
        .iter()
        .filter(|f| {
            std::fs::metadata(root.join(&entry.app_subdir).join(&f.name))
                .is_ok_and(|m| m.len() == f.size)
        })
        .count()
}

/// Name of the file in a model's folder that records which manifest revision
/// its files were verified against (#202). Like a runtime pack's `.sha256`,
/// it is written only after every file's hash has been checked.
const REVISION_MARKER: &str = ".revision";

/// The revision this model's files on disk were last verified against, or
/// `None` when they never were (not downloaded, or installed before the
/// marker existed).
#[must_use]
pub fn installed_revision(root: &Path, entry: &ManifestModel) -> Option<String> {
    std::fs::read_to_string(root.join(&entry.app_subdir).join(REVISION_MARKER))
        .ok()
        .map(|revision| revision.trim().to_owned())
}

/// Record that this model's files are the manifest revision. Call only once
/// every file's sha256 has been checked against the manifest.
pub fn mark_revision(root: &Path, entry: &ManifestModel) -> Result<(), String> {
    let marker = root.join(&entry.app_subdir).join(REVISION_MARKER);
    std::fs::write(&marker, &entry.revision).map_err(|e| format!("write {}: {e}", marker.display()))
}

/// Whether this model's files belong to another release's revision and need
/// downloading again (#202), as opposed to never downloaded or damaged. The
/// marker alone decides: sizes can't tell, because a retrained model is
/// exactly as large as the one it replaces. Such a model is never loaded;
/// its output would be cached as the new revision's.
#[must_use]
pub fn update_required(root: &Path, entry: &ManifestModel) -> bool {
    installed_revision(root, entry).is_some_and(|revision| revision != entry.revision)
}

#[cfg(test)]
mod tests {
    use super::{
        ManifestFile, ManifestModel, installed_revision, load, mark_revision, update_required,
    };

    /// "Update required" (#202) is a marker naming another revision, whether
    /// or not the files look present: a re-pinned model can be the same
    /// size. No marker means never downloaded (or not yet stamped), which is
    /// a different state.
    #[test]
    fn update_required_follows_the_marker() -> Result<(), String> {
        let root = std::env::temp_dir().join(format!("ccm-revision-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let entry = |revision: &str| ManifestModel {
            digit_level: 2,
            app_subdir: "two".to_owned(),
            display_name: "Two".to_owned(),
            hf_repo: "r".to_owned(),
            revision: revision.to_owned(),
            files: vec![ManifestFile {
                name: "model.onnx".to_owned(),
                sha256: String::new(),
                size: 4,
            }],
        };
        let dir = root.join("two");
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;

        // Never downloaded: missing, not an update.
        assert_eq!(installed_revision(&root, &entry("old")), None);
        assert!(!update_required(&root, &entry("old")));

        std::fs::write(dir.join("model.onnx"), b"1234").map_err(|e| e.to_string())?;
        mark_revision(&root, &entry("old"))?;
        assert_eq!(
            installed_revision(&root, &entry("old")).as_deref(),
            Some("old")
        );
        assert!(!update_required(&root, &entry("old")));

        // A new revision whose file is the same size as the old one: the
        // files look present, and the marker still says they are stale.
        assert_eq!(super::files_present(&root, &entry("new")), 1);
        assert!(update_required(&root, &entry("new")));

        // A file going missing under a current marker is damage, not an
        // update.
        std::fs::remove_file(dir.join("model.onnx")).map_err(|e| e.to_string())?;
        assert!(update_required(&root, &entry("new")));
        assert!(!update_required(&root, &entry("old")));
        std::fs::remove_dir_all(&root).map_err(|e| e.to_string())
    }

    /// The committed models.toml must parse into the typed manifest: three
    /// digit levels, three files each, full-SHA revisions, well-formed
    /// hashes. Catches a hand-edited or truncated manifest at test time
    /// instead of first launch.
    #[test]
    fn embedded_manifest_is_well_formed() -> Result<(), String> {
        let manifest = load()?;
        assert_eq!(manifest.model.len(), 3);
        let mut digits: Vec<u8> = manifest.model.iter().map(|m| m.digit_level).collect();
        digits.sort_unstable();
        assert_eq!(digits, vec![2, 4, 6]);
        for model in &manifest.model {
            assert_eq!(
                model.revision.len(),
                40,
                "{}: revision must be a full commit SHA",
                model.hf_repo
            );
            assert_eq!(model.files.len(), 3, "{}: expected 3 files", model.hf_repo);
            for file in &model.files {
                assert_eq!(
                    file.sha256.len(),
                    64,
                    "{}/{}: malformed sha256",
                    model.hf_repo,
                    file.name
                );
                assert!(file.size > 0);
            }
        }
        Ok(())
    }
}
