// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * List user-supplied themes (built-in themes are registered on the frontend).
 * Unparseable or invalid files are skipped, not fatal, so one bad file can't hide
 * the rest.
 */
async listThemes() : Promise<Result<ThemeSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_themes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read one user theme by id.
 */
async readTheme(id: string) : Promise<Result<Theme, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_theme", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read settings, creating a default file on first run.
 */
async readSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist settings. Validates `activeTheme` is a well-formed id.
 */
async writeSettings(settings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClassificationCoverage(datasetId: string) : Promise<Result<CoverageRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_classification_coverage", { datasetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCoursesWithResults(req: ListCoursesRequest) : Promise<Result<CoursePage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_courses_with_results", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Convenience IPC: return the manifest-active `models.id` for a digit level
 * so the frontend can request joined results without owning the surrogate id
 * space. Resolved through the catalog — never by SQL guessing, which would
 * happily pick a stale row from an earlier model family.
 */
async modelIdForDigitLevel(digitLevel: number) : Promise<Result<number | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("model_id_for_digit_level", { digitLevel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read up to [`SAMPLE_ROW_LIMIT`] rows from the CSV at `path`, returning the
 * headers + sample rows + file metadata. Never persists anything — the only
 * side effect is opening the file for reading.
 */
async previewCsv(path: string) : Promise<Result<CsvPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_csv", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDatasets() : Promise<Result<DatasetSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_datasets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a dataset's courses (joined with the requested models' cached
 * classifications + taxonomy titles) to a CSV the user picks via the native
 * save dialog. Returns `None` when the user cancels the dialog.
 */
async exportResults(req: ExportRequest) : Promise<Result<ExportOutcome | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_results", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCsv(req: ImportRequest) : Promise<Result<ImportStarted, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMetrics() : Promise<Result<AppMetrics, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request cancellation of the in-flight model download. The chunk loop
 * honors it within one read; the partial file is deleted. Returns `false`
 * when no download was active.
 */
async cancelDownload() : Promise<boolean> {
    return await TAURI_INVOKE("cancel_download");
},
/**
 * Download every missing manifest file from its pinned HF revision into the
 * data-dir models path, sha256-verifying as it streams. Connected builds
 * only — the airgap bundle ships its models read-only in the resource dir.
 */
async downloadModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load models from disk into the store. No-op when already loaded; errors if
 * a load is in flight or files are missing. Slow (~5-15 s), so it runs on a
 * blocking thread and the UI shows `loading` from `models_status`.
 */
async loadModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async modelsStatus() : Promise<Result<ModelStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("models_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear the store and load fresh — the settings path for changes that only
 * take effect at session build time (EPI-73: EP priority reorder). Unlike
 * `load_models`, already-loaded is not a no-op. A run in flight finishes on
 * its `Arc` of the old registry; new runs see the new sessions.
 */
async reloadModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download + verify + install a runtime pack into the data dir. The new pack
 * is picked up at the next app launch (init-once); the UI says so. Connected
 * builds only — airgap has no network by definition.
 */
async downloadRuntime(packId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_runtime", { packId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restart the app (EPI-94): the one way to switch runtime packs, since ONNX
 * Runtime loads exactly once per process.
 */
async relaunchApp() : Promise<void> {
    await TAURI_INVOKE("relaunch_app");
},
async runtimeStatus() : Promise<Result<RuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("runtime_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Most recent run for a dataset, or `None` if the dataset has never been
 * classified. The dataset tab's run surface card derives from this — backend
 * state, not component memory — so it survives tab close/reopen and app
 * restart (EPI-68).
 */
async getLatestRun(datasetId: string) : Promise<Result<RunDetail | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_latest_run", { datasetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRun(id: string) : Promise<Result<RunDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_run", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRuns() : Promise<Result<RunSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request a graceful pause of an in-flight run. The worker stops at its next
 * batch boundary — after the current batch's results and progress are flushed
 * in the usual transaction — and finalizes the run as `interrupted` (resumable
 * later; see EPI-38/EPI-39). Returns `true` if a running worker was signalled,
 * `false` if the run wasn't active (already terminal, or unknown id).
 */
async pauseRun(runId: string) : Promise<boolean> {
    return await TAURI_INVOKE("pause_run", { runId });
},
/**
 * Resume an `interrupted` run (EPI-38). Same worker, same run id: the row
 * flips back to `running` with `resume_count` bumped, and the pipeline
 * selects only the courses still missing a result for this model — progress
 * continues from where it stopped (`total - remaining`), never from zero.
 * Idempotent by construction: anything already in `inference_results` is
 * never recomputed.
 */
async resumeRun(runId: string) : Promise<Result<StartRunResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_run", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startRun(req: StartRunRequest) : Promise<Result<StartRunResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_run", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
modelDownloadProgress: ModelDownloadProgress,
modelsStateChanged: ModelsStateChanged,
runtimeDownloadProgress: RuntimeDownloadProgress,
runtimeStateChanged: RuntimeStateChanged
}>({
modelDownloadProgress: "model-download-progress",
modelsStateChanged: "models-state-changed",
runtimeDownloadProgress: "runtime-download-progress",
runtimeStateChanged: "runtime-state-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type AppMetrics = { datasets: number; courses: number; runs: number; completedRuns: number; 
/**
 * Distinct `(model_id, content_hash)` rows in `inference_results`.
 */
classifications: number; 
/**
 * Sum of `runs.cache_hits` divided by sum of `runs.rows_processed`, both
 * across all runs. `None` when no rows have been processed yet (avoids a
 * noisy 0% on a fresh DB).
 */
cacheHitRate: number | null }
/**
 * A `--ui-color-{role}-{shade}` ramp. Each shade is optional so a theme can
 * override a subset. Field names render to the numeric shade keys.
 */
export type ColorRamp = { "50"?: string | null; "100"?: string | null; "200"?: string | null; "300"?: string | null; "400"?: string | null; "500"?: string | null; "600"?: string | null; "700"?: string | null; "800"?: string | null; "900"?: string | null; "950"?: string | null }
/**
 * The role color ramps (`--ui-color-<role>-<shade>`).
 */
export type ColorRamps = { primary?: ColorRamp | null; secondary?: ColorRamp | null; success?: ColorRamp | null; info?: ColorRamp | null; warning?: ColorRamp | null; error?: ColorRamp | null; neutral?: ColorRamp | null }
/**
 * `light` / `dark` — drives `VueUse` `useColorMode().preference` on the frontend.
 */
export type ColorScheme = "light" | "dark"
export type CoursePage = { rows: CourseRow[]; total: number }
export type CourseRow = { id: number; rowIndex: number; subjectCode: string | null; catalogNumber: string | null; courseTitle: string | null; contentHash: string; 
/**
 * Canonical CCM code from `inference_results` for the requested model;
 * `None` when there's no result yet (or no `model_id` was requested).
 */
classification: string | null; 
/**
 * Softmax confidence at argmax, `(0, 1]`. See `docs/model-confidence.md`.
 */
probability: number | null; 
/**
 * Official CCM title for the code, joined from `ccm_taxonomy`. For
 * 4-digit codes (no published taxonomy exists) and 6-digit codes missing
 * from the table, this is the 2-digit parent's title — `ccm_title_level`
 * says which level matched.
 */
ccmTitle: string | null; ccmTitleShort: string | null; 
/**
 * Only 6-digit taxonomy rows carry descriptions.
 */
ccmDescription: string | null; 
/**
 * Digit level the title came from (the model's own level, or 2 for the
 * parent fallback); `None` when no taxonomy row matched.
 */
ccmTitleLevel: number | null }
/**
 * Per-model classification coverage for one dataset: how many of its courses
 * already have a cached result for each manifest-active model. Drives the
 * dataset tab's per-level coverage chips and the pre-run confirm panel's
 * "already classified" count (EPI-68). Counts are course-level (duplicate
 * content hashes count once per course row), matching what a run would report.
 */
export type CoverageRow = { modelId: number; digitLevel: number; classified: number; total: number }
export type CsvPreview = { headers: string[]; sampleRows: string[][]; totalColumns: number; sizeBytes: number }
/**
 * One row in the Datasets activity tab. Timestamps are serialized as ISO-8601
 * strings rather than `chrono::DateTime` so we don't need a specta-chrono
 * integration just yet — the frontend treats them as opaque sortable strings.
 */
export type DatasetSummary = { id: string; title: string; sourceKind: string; importedAt: string; 
/**
 * Read straight from `datasets.row_count`, which the import worker keeps
 * up to date (live ticks during streaming, finalized in `mark_ready`).
 * Datasets are otherwise immutable, so there's no fallback `COUNT(*)`.
 */
rowCount: number; 
/**
 * `importing` while the background worker is still streaming rows in,
 * `ready` when complete, `failed` when the worker errored.
 */
importState: string; importError: string | null }
/**
 * Last-known download position for one digit level, kept server-side so a
 * freshly-mounted client renders the true state from `models_status` without
 * having caught any progress events (EPI-74).
 */
export type DownloadSnapshot = { file: string; received: number; total: number }
/**
 * Execution providers the app knows how to register, in the shape the
 * settings priority list stores. `Cpu` is a real list entry ("allowed as
 * fallback"), not an implicit default — a user who wants CPU-only moves it
 * to the top.
 */
export type EpKind = "tensorrt" | "cuda" | "directml" | "coreml" | "cpu"
export type ExportOutcome = { path: string; rows: number }
export type ExportRequest = { datasetId: string; 
/**
 * Models whose classifications populate the `ccm*` column sets — one
 * set per model, ordered by digit level (EPI-80). Rows without a cached
 * result for a model export with that model's cells empty. Must be
 * non-empty with distinct digit levels.
 */
modelIds: number[]; 
/**
 * Emit the numbered top-5 candidate columns (`ccm…_code1` …
 * `ccm…_title5`) per exported model. Export-dialog toggle (EPI-98).
 */
includeTopCandidates: boolean; rowMode: RowMode }
export type ImportRequest = { path: string; 
/**
 * Falls back to the filename when null/blank.
 */
displayName: string | null; 
/**
 * Optional row cap; `None` means import every row.
 */
limit: number | null }
/**
 * Response from `import_csv`: the dataset has been queued and is already
 * streaming rows in. The frontend polls `list_datasets` from here.
 */
export type ImportStarted = { datasetId: string; sourceFileId: number }
export type ListCoursesRequest = { datasetId: string; 
/**
 * Optional model id for the joined classification + probability columns.
 * `None` means the joined columns come back as `null`.
 */
modelId: number | null; 
/**
 * Key-set cursor: include rows with `row_index >= cursor`. `None` (and 0)
 * mean "from the start". The frontend hands back the row index of the
 * last row of a page + 1 to advance. Replaces `OFFSET` because `DuckDB`'s
 * `TopN` plan for `ORDER BY row_index LIMIT n OFFSET m` ignores the
 * `(dataset_id, row_index)` index and scans the whole partition;
 * the range predicate lets the index drive the scan.
 */
cursor: number | null; limit: number }
/**
 * Per-file download progress. `received`/`total` are bytes; `bytes_per_sec`
 * is measured over the emission window (EPI-65). The frontend derives
 * percentages.
 */
export type ModelDownloadProgress = { digitLevel: number; file: string; received: number; total: number; bytesPerSec: number }
export type ModelStatus = { digitLevel: number; displayName: string; hfRepo: string; revision: string; filesTotal: number; 
/**
 * Files on disk with the manifest's exact size. Full sha256 verification
 * happens during download, not on status polls.
 */
filesPresent: number; totalBytes: number; loaded: boolean; loading: boolean; 
/**
 * Whether a download is in flight app-wide (same value on every row).
 * This — not any component-local pending flag — gates the Download
 * button (EPI-74).
 */
downloading: boolean; 
/**
 * This level's last-known download position, when a download has
 * touched it. Hydrates a freshly-mounted progress bar.
 */
download: DownloadSnapshot | null }
/**
 * Coarse "something about model state changed" signal — emitted after a file
 * finishes downloading, a load starts/completes, or either fails. The
 * frontend responds by refetching `models_status`.
 */
export type ModelsStateChanged = Record<string, never>
/**
 * Row granularity of the export (EPI-78).
 */
export type RowMode = 
/**
 * One output row per input row (source fidelity, mergeable back onto
 * the original file).
 */
"all" | 
/**
 * One output row per distinct classified input (`content_hash`).
 * Duplicate inputs share one cached result by construction; the
 * representative row is the first occurrence (lowest `row_index`).
 */
"unique"
/**
 * Full run detail for the run-tab body. Same shape as [`RunSummary`] plus the
 * model digit level (resolved from the JSON `model_ids` array) and the
 * `unique_inputs_done` + `error_message` fields the summary view drops.
 */
export type RunDetail = { id: string; datasetId: string; datasetTitle: string; description: string | null; state: string; digitLevel: number | null; 
/**
 * How many models the run covers (EPI-96). Row counters are in
 * row×model units — the UI divides by this to talk about dataset rows.
 */
modelCount: number; rowsTotal: number | null; rowsProcessed: number | null; uniqueInputsDone: number | null; cacheHits: number | null; createdAt: string; startedAt: string | null; completedAt: string | null; lastProgressAt: string | null; errorMessage: string | null; executionProvider: string | null; resumeCount: number; resumable: boolean; resumeBlockers: string[] }
/**
 * One row in the Runs sidebar list. Joined with the dataset title so the UI
 * doesn't need a second IPC call to render a meaningful label.
 */
export type RunSummary = { id: string; datasetId: string; datasetTitle: string; description: string | null; state: string; 
/**
 * Resolved from the run's first `model_ids` entry so a list row can say
 * which model it was without a second IPC call (EPI-69).
 */
digitLevel: number | null; 
/**
 * How many models the run covers (EPI-96). Row counters are in
 * row×model units — the UI divides by this to talk about dataset rows.
 */
modelCount: number; rowsTotal: number | null; rowsProcessed: number | null; cacheHits: number | null; createdAt: string; startedAt: string | null; completedAt: string | null; lastProgressAt: string | null; resumeCount: number; 
/**
 * Whether `resume_run` would accept this run right now (EPI-69).
 * Computed at read time — never persisted — so external changes (models
 * swapped, files deleted) are reflected immediately.
 */
resumable: boolean; 
/**
 * Machine-stable reasons when an `interrupted` run can't resume
 * (`model_superseded`, `model_not_loaded`). Empty when resumable, and
 * for states resume doesn't apply to.
 */
resumeBlockers: string[] }
/**
 * Per-pack download progress, mirroring `models::ModelDownloadProgress`.
 */
export type RuntimeDownloadProgress = { packId: string; received: number; total: number; bytesPerSec: number }
export type RuntimePackStatus = { id: string; displayName: string; 
/**
 * EPs the pack claims to carry (manifest metadata; empty = libs pack).
 */
eps: string[]; sizeBytes: number; installed: boolean; 
/**
 * Whether this is the pack the running process loaded (always false for
 * libs packs — they are preloaded next to a runtime pack, not loaded as
 * one).
 */
active: boolean; 
/**
 * Companion libs pack id, when this runtime pack has one (EPI-84).
 */
libs: string | null }
/**
 * Coarse "runtime pack state changed" signal — emitted when a pack install
 * finishes or fails; the frontend refetches `runtime_status`.
 */
export type RuntimeStateChanged = Record<string, never>
export type RuntimeStatus = { ortVersion: string; 
/**
 * Pack the running process loaded (fixed until relaunch).
 */
activePackId: string; 
/**
 * EP the loaded models actually run on; `None` until models load.
 */
resolvedEp: string | null; 
/**
 * Platform EPs in the shape the settings priority list stores, for the
 * settings UI to render reorderable rows without hardcoding.
 */
platformDefaultPriority: EpKind[]; packs: RuntimePackStatus[]; 
/**
 * Startup runtime conditions worth a warning in Settings (EPI-87):
 * damaged-pack fallback, missing CUDA directory, failed preloads.
 */
notices: string[] }
/**
 * The semantic `--ui-*` tokens. Field names render to the token suffix; the
 * applier prepends `--ui-` (e.g. `bg_muted` -> `--ui-bg-muted`).
 */
export type SemanticTokens = { bg?: string | null; "bg-muted"?: string | null; "bg-elevated"?: string | null; "bg-accented"?: string | null; "bg-inverted"?: string | null; text?: string | null; "text-muted"?: string | null; "text-dimmed"?: string | null; "text-toned"?: string | null; "text-highlighted"?: string | null; "text-inverted"?: string | null; border?: string | null; "border-muted"?: string | null; "border-accented"?: string | null; "border-inverted"?: string | null; primary?: string | null; secondary?: string | null; success?: string | null; info?: string | null; warning?: string | null; error?: string | null; radius?: string | null }
/**
 * General application settings. `activeTheme` references a theme by id; design
 * tokens themselves live in `themes/*.json`, not here.
 */
export type Settings = { activeTheme: string; 
/**
 * Execution-provider priority for inference (EPI-73), most preferred
 * first. `cpu` is a list entry meaning "allowed as fallback" — the one
 * mechanism, no separate GPU toggle. Reordering takes effect on the
 * next model load; switching *packs* (cpu↔cuda dylib) needs a relaunch.
 * `serde(default)` keeps pre-EPI-73 settings.json files parsing under
 * `deny_unknown_fields`.
 */
executionProviders?: EpKind[]; 
/**
 * Cap on ORT's intra-op CPU threads during inference (EPI-83).
 * `0` = auto (ORT default: all physical cores); any value below 1 or
 * above the machine's cores also behaves as auto — clamp semantics,
 * no error states. Applied at session build; rides `reload_models`.
 */
maxCpuThreads?: number; 
/**
 * Directory holding CUDA/cuDNN libraries to preload at startup (EPI-84)
 * — for users whose CUDA lives in a conda env or pip venv
 * (`site-packages/nvidia`) instead of a system install. Takes precedence
 * over the downloadable support-libs pack; changing it needs a relaunch
 * (preload is process-lifetime).
 */
cudaLibraryDir?: string | null; 
/**
 * Runtime pack the user explicitly activated in Settings → Compute
 * (EPI-94). Checked before the EP-priority scan at startup, so an
 * explicit choice can never be shadowed by manifest order. `None` — or a
 * pack that is no longer installed — falls back to the scan, whose
 * terminal fallback is the bundled CPU pack. Switching packs requires a
 * relaunch (ONNX Runtime is init-once).
 */
preferredPack?: string | null }
export type StartRunRequest = { 
/**
 * A run always classifies the dataset with every manifest model
 * (EPI-96) — there is no level to pick.
 */
datasetId: string }
/**
 * Response from `start_run`: the run has been queued and is already updating
 * its own row. The frontend polls `get_run(run_id)` from here.
 */
export type StartRunResponse = { runId: string; rowsTotal: number }
/**
 * A full theme. `id` is the filename stem (set after load), never read from the
 * file body — `deny_unknown_fields` rejects an `id` key in the JSON.
 */
export type Theme = { name: string; colorScheme: ColorScheme; font?: string | null; tokens?: SemanticTokens; colors?: ColorRamps }
/**
 * Lightweight listing entry (no token payload) for the theme registry.
 */
export type ThemeSummary = { id: string; name: string; colorScheme: ColorScheme }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
